# Generated by Django 6.0.3 on 2026-03-14 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author_image1',
            new_name='author_image',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='author_image2',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='author_image3',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='author_image4',
        ),
    ]
