# Generated by Django 6.0.3 on 2026-03-14 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_author_image1_comment_author_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='image1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='image3',
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(upload_to='portfolio_img'),
        ),
    ]
